import { Metadata } from "next";

export const DEFAULT_ROOT_METADATA: Metadata = {
    title: "Template App",
    description: "Generated by Template App",
};

export const COOKIE_NAMES = {
    LOCALE: "locale",
} as const;
